
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - gcp.easystacks.crossplane.io
  resources:
  - easygcps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gcp.easystacks.crossplane.io
  resources:
  - easygcps/status
  verbs:
  - get
  - patch
  - update
